services:
  parser-api:
    container_name: parser-api
    restart: on-failure
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    read_only: true
    tmpfs:
      - /tmp
    mem_limit: 1536m
    ports:
      - '127.0.0.1:8080:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8080/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      mpp-viewer:


networks:
  mpp-viewer:
    internal: true